"""Add profiles table

Revision ID: 3aec2dde10b4
Revises: 
Create Date: 2026-09-06 17:56:27.108807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app


# revision identifiers, used by Alembic.
revision: str = '3aec2dde10b4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auction_format',
    sa.Column('id', app.models.guid.GUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('format_type', sa.Enum('MEGA', 'GENERIC', name='formattype'), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('salary_cap', sa.Float(), nullable=False),
    sa.Column('max_squad_size', sa.Integer(), nullable=False),
    sa.Column('max_overseas', sa.Integer(), nullable=False),
    sa.Column('max_overseas_playing', sa.Integer(), nullable=False),
    sa.Column('retention_rules_json', sa.JSON(), nullable=True),
    sa.Column('bid_increment_tiers_json', sa.JSON(), nullable=True),
    sa.Column('player_set_order_json', sa.JSON(), nullable=True),
    sa.Column('rtm_enabled', sa.Boolean(), nullable=True),
    sa.Column('rtm_rules_json', sa.JSON(), nullable=True),
    sa.Column('unsold_reentry_enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player',
    sa.Column('id', app.models.guid.GUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('nationality', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('BATSMAN', 'BOWLER', 'ALL_ROUNDER', 'WICKET_KEEPER', name='playerrole'), nullable=False),
    sa.Column('specialization', sa.String(), nullable=True),
    sa.Column('batting_style', sa.String(), nullable=True),
    sa.Column('bowling_style', sa.String(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('ipl_experience_years', sa.Integer(), nullable=True),
    sa.Column('base_price', sa.Float(), nullable=False),
    sa.Column('current_team_id', app.models.guid.GUID(), nullable=True),
    sa.Column('batting_avg', sa.Float(), nullable=True),
    sa.Column('strike_rate', sa.Float(), nullable=True),
    sa.Column('bowling_avg', sa.Float(), nullable=True),
    sa.Column('economy', sa.Float(), nullable=True),
    sa.Column('wickets', sa.Integer(), nullable=True),
    sa.Column('runs', sa.Integer(), nullable=True),
    sa.Column('matches_played', sa.Integer(), nullable=True),
    sa.Column('catches', sa.Integer(), nullable=True),
    sa.Column('stumpings', sa.Integer(), nullable=True),
    sa.Column('run_outs', sa.Integer(), nullable=True),
    sa.Column('fitness_score', sa.Float(), nullable=True),
    sa.Column('injury_history_json', sa.JSON(), nullable=True),
    sa.Column('workload_index', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_player_name'), 'player', ['name'], unique=False)
    op.create_table('team',
    sa.Column('id', app.models.guid.GUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('short_name', sa.String(), nullable=False),
    sa.Column('logo_url', sa.String(), nullable=True),
    sa.Column('primary_color', sa.String(), nullable=True),
    sa.Column('secondary_color', sa.String(), nullable=True),
    sa.Column('total_budget', sa.Float(), nullable=False),
    sa.Column('remaining_budget', sa.Float(), nullable=False),
    sa.Column('max_squad_size', sa.Integer(), nullable=False),
    sa.Column('current_squad_size', sa.Integer(), nullable=True),
    sa.Column('retained_players_json', sa.JSON(), nullable=True),
    sa.Column('strategy_profile', sa.Enum('AGGRESSIVE', 'BALANCED', 'CONSERVATIVE', name='strategyprofile'), nullable=True),
    sa.Column('home_ground', sa.String(), nullable=True),
    sa.Column('owner', sa.String(), nullable=True),
    sa.Column('coach', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('short_name')
    )
    op.create_table('auction_session',
    sa.Column('id', app.models.guid.GUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'LIVE', 'COMPLETED', name='auctionstatus'), nullable=True),
    sa.Column('format_id', app.models.guid.GUID(), nullable=False),
    sa.Column('total_rounds', sa.Integer(), nullable=True),
    sa.Column('current_round', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['format_id'], ['auction_format.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('franchise_user',
    sa.Column('id', sa.UUID(), nullable=False, comment='Matches Supabase auth.users id'),
    sa.Column('franchise_id', sa.UUID(), nullable=True),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['franchise_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profiles',
    sa.Column('id', app.models.guid.GUID(), nullable=False),
    sa.Column('user_id', app.models.guid.GUID(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('custom_team_name', sa.String(), nullable=True),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('franchise_id', app.models.guid.GUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['franchise_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_profiles_id'), 'profiles', ['id'], unique=False)
    op.create_table('simulation_run',
    sa.Column('id', app.models.guid.GUID(), nullable=False),
    sa.Column('type', sa.Enum('SCENARIO', 'DIGITAL_TWIN', 'DRAFT', name='simulationtype'), nullable=False),
    sa.Column('franchise_id', app.models.guid.GUID(), nullable=False),
    sa.Column('created_by_user_id', app.models.guid.GUID(), nullable=True),
    sa.Column('config_json', sa.JSON(), nullable=True),
    sa.Column('results_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['franchise_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team_squad_slot',
    sa.Column('id', app.models.guid.GUID(), nullable=False),
    sa.Column('team_id', app.models.guid.GUID(), nullable=False),
    sa.Column('player_id', app.models.guid.GUID(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('purchase_price', sa.Float(), nullable=False),
    sa.Column('purchase_round', sa.Integer(), nullable=True),
    sa.Column('is_retained', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('auction_event',
    sa.Column('id', app.models.guid.GUID(), nullable=False),
    sa.Column('auction_session_id', app.models.guid.GUID(), nullable=False),
    sa.Column('player_id', app.models.guid.GUID(), nullable=False),
    sa.Column('event_type', sa.Enum('PLAYER_PRESENTED', 'BID', 'SOLD', 'UNSOLD', 'RTM_EXERCISED', 'RTM_DECLINED', name='eventtype'), nullable=False),
    sa.Column('bid_amount', sa.Float(), nullable=True),
    sa.Column('bidding_team_id', app.models.guid.GUID(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['auction_session_id'], ['auction_session.id'], ),
    sa.ForeignKeyConstraint(['bidding_team_id'], ['team.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('auction_result',
    sa.Column('id', app.models.guid.GUID(), nullable=False),
    sa.Column('session_id', app.models.guid.GUID(), nullable=False),
    sa.Column('player_id', app.models.guid.GUID(), nullable=False),
    sa.Column('winning_team_id', app.models.guid.GUID(), nullable=True),
    sa.Column('final_price', sa.Float(), nullable=True),
    sa.Column('round_number', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['auction_session.id'], ),
    sa.ForeignKeyConstraint(['winning_team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('simulation_snapshot',
    sa.Column('id', app.models.guid.GUID(), nullable=False),
    sa.Column('run_id', app.models.guid.GUID(), nullable=False),
    sa.Column('step_number', sa.Integer(), nullable=False),
    sa.Column('state_json', sa.JSON(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['simulation_run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('simulation_snapshot')
    op.drop_table('auction_result')
    op.drop_table('auction_event')
    op.drop_table('team_squad_slot')
    op.drop_table('simulation_run')
    op.drop_index(op.f('ix_profiles_id'), table_name='profiles')
    op.drop_table('profiles')
    op.drop_table('franchise_user')
    op.drop_table('auction_session')
    op.drop_table('team')
    op.drop_index(op.f('ix_player_name'), table_name='player')
    op.drop_table('player')
    op.drop_table('auction_format')
    # ### end Alembic commands ###
